# pre-trained-model(Multiple_Input_Lstm)

- developer: mehdi sahraei
- [link github](https://github.com/mehdisahraeei)

### Importing

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math
import tensorflow as tf
from numpy import array
from sklearn.preprocessing import MinMaxScaler

### loading model

In [4]:
# loading model
model = tf.keras.models.load_model('savedata2')

### Testing model

#### new testing
- we must change dim

In [6]:
test_norm = np.array([[309000, 307330],[307690, 304790],[309040, 308330]])
test_norm = test_norm.astype('float128')
test_norm = test_norm.reshape(-1,1)
print(test_norm.shape)
print(test_norm)

(6, 1)
[[309000.]
 [307330.]
 [307690.]
 [304790.]
 [309040.]
 [308330.]]


In [7]:
scaler = MinMaxScaler(feature_range = (0,1))
test_norm = scaler.fit_transform(test_norm)
print(test_norm[:],'\n')
print(test_norm.shape)

[[0.99058824]
 [0.59764706]
 [0.68235294]
 [0.        ]
 [1.        ]
 [0.83294118]] 

(6, 1)


In [8]:
test_ = array([[0.99058824, 0.59764706],[0.68235294, 0.        ],[1.      , 0.83294118]])
test_ = test_.reshape(1,3,2)


print(test_.shape,'\n')
print(test_)

(1, 3, 2) 

[[[0.99058824 0.59764706]
  [0.68235294 0.        ]
  [1.         0.83294118]]]


In [9]:
y_hat = model.predict(test_)
y_hat

1/1 [==============================] - 0s 217ms/step


array([[0.69331026, 0.5517338 ]], dtype=float32)

In [10]:
y_hat = scaler.inverse_transform(y_hat)
y_hat

array([[307736.6 , 307134.88]], dtype=float32)